---
kind: pipeline
type: docker
name: test & deploy

steps:
  - name: test
    image: node:lts-alpine
    commands:
      - yarn --immutable --immutable-cache
  - name: update server files
    image: alpine/git
    when:
      branch: master
    volumes:
      - name: server
        path: /server
    commands:
      - cd /server/_repos/portfolio
      - git config --global --add safe.directory /server/_repos/portfolio
      - git pull --rebase
  - name: deploy to server
    image: docker/compose
    when:
      branch: master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - cd /server
      - ./start.sh portfolio --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server
---
kind: signature
hmac: 30af6d31f66da6769f70a8490c3e627e431007cf9384f0acb29bf3f0eef6c961
