---
kind: pipeline
type: docker
name: test & deploy

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm ci
  - name: update server files
    image: alpine/git
    when:
      branch: master
    volumes:
      - name: repo
        path: /_repos/portfolio
    commands:
      - cd /_repos/portfolio && git pull --rebase
  - name: deploy to server
    image: docker/compose
    when:
      branch: master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: repo
        path: /_repos/portfolio
      - name: compose
        path: /_compose/portfolio
    commands:
      - docker-compose -f /_compose/portfolio/docker-compose.yml up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: repo
    host:
      path: /server/_repos/portfolio
  - name: compose
    host:
      path: /server/_compose/portfolio
---
kind: signature
hmac: 9849dcd1c3a3e068de0e91fb3c4f1224ed6cea731f5976933b4933f82b17320c

...
