---
kind: pipeline
type: docker
name: test & deploy

steps:
  - name: test
    image: node:lts-alpine
    commands:
      - npm ci
  - name: update server files
    image: alpine/git
    when:
      branch: master
    volumes:
      - name: server
        path: /server
    commands:
      - cd /server/_repos/portfolio
      - git pull --rebase
  - name: deploy to server
    image: docker/compose
    when:
      branch: master
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - cd /server
      - ./start.sh portfolio --build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server
---
kind: signature
hmac: 547ca6af68dddf4068d17af06f5cd5b4006e49c16d196ef8b3d0963c91219c4f
